// Generated by GitHub Copilot
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

const repositoryName = process.env.GITHUB_REPOSITORY?.split("/")[1];
const isPagesBuild = process.env.GITHUB_ACTIONS === "true";

/**
 * Generated by GitHub Copilot
 * Build and dev server configuration for local and GitHub Pages deployments.
 */
export default defineConfig({
  plugins: [react()],
  base: isPagesBuild && repositoryName ? `/${repositoryName}/` : "/",
  server: {
    port: 5173,
    host: true,
    proxy: {
      "/api": {
        target: "http://localhost:8000",
        changeOrigin: true
      }
    }
  }
});
