// Generated by GitHub Copilot
interface MetricCardProps {
  title: string;
  value: string;
  tone: "neutral" | "alert" | "ok";
}

/**
 * Generated by GitHub Copilot
 * Reusable metric card with semantic color states for summary KPIs.
 */
export function MetricCard({ title, value, tone }: MetricCardProps): JSX.Element {
  return (
    <article className={`metric-card metric-card--${tone}`} aria-label={title}>
      <h3>{title}</h3>
      <p>{value}</p>
    </article>
  );
}
