# Generated by GitHub Copilot
"""API integration tests for drift-watch backend."""

from fastapi.testclient import TestClient

from app.main import app


client = TestClient(app)


def _build_rows(offset: int, length: int) -> list[dict[str, object]]:
    """Create deterministic rows for drift evaluation tests."""
    rows = []
    for index in range(length):
        rows.append(
            {
                "income": float(50000 + (index * 100) + offset),
                "region": "east" if index % 2 == 0 else "west",
            }
        )
    return rows


def test_health_endpoint() -> None:
    """Ensure liveness endpoint responds successfully."""
    response = client.get("/health")
    assert response.status_code == 200
    assert response.json()["status"] == "ok"


def test_ready_endpoint() -> None:
    """Ensure readiness endpoint responds successfully."""
    response = client.get("/ready")
    assert response.status_code == 200
    assert response.json()["status"] == "ready"


def test_feature_drift_evaluation_success() -> None:
    """Validate successful drift evaluation response payload."""
    payload = {
        "schema_name": "credit-risk-model-v1",
        "features": [
            {
                "name": "income",
                "kind": "numeric",
                "bins": 10,
                "alert_threshold": 0.1,
            },
            {
                "name": "region",
                "kind": "categorical",
                "alert_threshold": 0.1,
            },
        ],
        "reference_rows": _build_rows(offset=0, length=80),
        "current_rows": _build_rows(offset=9000, length=80),
    }

    response = client.post("/api/v1/drift/evaluate", json=payload)
    assert response.status_code == 200

    parsed = response.json()
    assert parsed["summary"]["schema_name"] == "credit-risk-model-v1"
    assert parsed["summary"]["total_features"] == 2
    assert len(parsed["results"]) == 2


def test_feature_drift_invalid_feature_name() -> None:
    """Reject malformed feature names to prevent unsafe payloads."""
    payload = {
        "schema_name": "credit-risk-model-v1",
        "features": [{"name": "income;drop", "kind": "numeric"}],
        "reference_rows": _build_rows(offset=0, length=40),
        "current_rows": _build_rows(offset=1000, length=40),
    }

    response = client.post("/api/v1/drift/evaluate", json=payload)
    assert response.status_code == 422


def test_concept_drift_numeric_success() -> None:
    """Validate concept drift endpoint for numeric target windows."""
    reference_target = [float(0.2 + (index * 0.01)) for index in range(60)]
    current_target = [float(0.4 + (index * 0.01)) for index in range(60)]
    reference_prediction = [value + 0.05 for value in reference_target]
    current_prediction = [value + 0.20 for value in current_target]

    payload = {
        "reference_target": reference_target,
        "current_target": current_target,
        "reference_prediction": reference_prediction,
        "current_prediction": current_prediction,
        "alert_threshold": 0.1,
    }

    response = client.post("/api/v1/drift/concept", json=payload)
    assert response.status_code == 200
    parsed = response.json()
    assert parsed["status"] in {"stable", "alert"}
    assert len(parsed["results"]) >= 1


def test_concept_drift_prediction_length_validation() -> None:
    """Reject prediction payloads with mismatched lengths."""
    payload = {
        "reference_target": [1] * 40,
        "current_target": [2] * 40,
        "reference_prediction": [1] * 39,
        "current_prediction": [2] * 40,
    }

    response = client.post("/api/v1/drift/concept", json=payload)
    assert response.status_code == 400
    assert "length" in response.json()["detail"]
