# Generated by GitHub Copilot
"""API integration tests for drift-watch backend."""

from dataclasses import replace

from fastapi.testclient import TestClient

from app import main as main_module
from app.main import app


client = TestClient(app)


# Generated by GitHub Copilot
def _assert_error_contract(
    response,
    expected_status: int,
    expected_code: str,
    expected_message: str | None = None,
    expect_details: bool = False,
) -> None:
    """Validate normalized error envelope fields for API contract tests."""
    assert response.status_code == expected_status
    payload = response.json()
    assert isinstance(payload.get("error"), dict)
    assert payload["error"]["code"] == expected_code
    assert isinstance(payload["error"]["message"], str)
    if expected_message is not None:
        assert payload["error"]["message"] == expected_message
    assert isinstance(payload["error"]["request_id"], str)
    assert payload["error"]["request_id"]
    if expect_details:
        assert "details" in payload["error"]


def _build_rows(offset: int, length: int) -> list[dict[str, object]]:
    """Create deterministic rows for drift evaluation tests."""
    rows = []
    for index in range(length):
        rows.append(
            {
                "income": float(50000 + (index * 100) + offset),
                "region": "east" if index % 2 == 0 else "west",
            }
        )
    return rows


def test_health_endpoint() -> None:
    """Ensure liveness endpoint responds successfully."""
    response = client.get("/health")
    assert response.status_code == 200
    assert response.json()["status"] == "ok"


def test_ready_endpoint() -> None:
    """Ensure readiness endpoint responds successfully."""
    response = client.get("/ready")
    assert response.status_code == 200
    assert response.json()["status"] == "ready"


def test_feature_drift_evaluation_success() -> None:
    """Validate successful drift evaluation response payload."""
    payload = {
        "schema_name": "credit-risk-model-v1",
        "features": [
            {
                "name": "income",
                "kind": "numeric",
                "bins": 10,
                "alert_threshold": 0.1,
            },
            {
                "name": "region",
                "kind": "categorical",
                "alert_threshold": 0.1,
            },
        ],
        "reference_rows": _build_rows(offset=0, length=80),
        "current_rows": _build_rows(offset=9000, length=80),
    }

    response = client.post("/api/v1/drift/evaluate", json=payload)
    assert response.status_code == 200

    parsed = response.json()
    assert parsed["summary"]["schema_name"] == "credit-risk-model-v1"
    assert parsed["summary"]["total_features"] == 2
    assert len(parsed["results"]) == 2


def test_feature_drift_invalid_feature_name() -> None:
    """Reject malformed payloads with normalized validation contract responses."""
    payload = {
        "schema_name": "credit-risk-model-v1",
        "reference_rows": _build_rows(offset=0, length=40),
        "current_rows": _build_rows(offset=1000, length=40),
    }

    response = client.post("/api/v1/drift/evaluate", json=payload)
    _assert_error_contract(
        response,
        expected_status=422,
        expected_code="validation_error",
        expected_message="request_validation_failed",
        expect_details=True,
    )


def test_concept_drift_numeric_success() -> None:
    """Validate concept drift endpoint for numeric target windows."""
    reference_target = [float(0.2 + (index * 0.01)) for index in range(60)]
    current_target = [float(0.4 + (index * 0.01)) for index in range(60)]
    reference_prediction = [value + 0.05 for value in reference_target]
    current_prediction = [value + 0.20 for value in current_target]

    payload = {
        "reference_target": reference_target,
        "current_target": current_target,
        "reference_prediction": reference_prediction,
        "current_prediction": current_prediction,
        "alert_threshold": 0.1,
    }

    response = client.post("/api/v1/drift/concept", json=payload)
    assert response.status_code == 200
    parsed = response.json()
    assert parsed["status"] in {"stable", "alert"}
    assert len(parsed["results"]) >= 1


def test_concept_drift_prediction_length_validation() -> None:
    """Reject prediction payloads with mismatched lengths."""
    payload = {
        "reference_target": [1] * 40,
        "current_target": [2] * 40,
        "reference_prediction": [1] * 39,
        "current_prediction": [2] * 40,
    }

    response = client.post("/api/v1/drift/concept", json=payload)
    _assert_error_contract(response, expected_status=400, expected_code="bad_request")
    assert "length" in response.json()["error"]["message"]


def test_phase1_auth_required_contract(monkeypatch) -> None:
    """Require API key on protected routes and return normalized unauthorized payloads."""
    monkeypatch.setattr(main_module, "settings", replace(main_module.settings, api_key="phase1-secret"))

    payload = {
        "schema_name": "phase1-auth",
        "features": [{"name": "income", "kind": "numeric", "bins": 10, "alert_threshold": 0.1}],
        "reference_rows": _build_rows(offset=0, length=40),
        "current_rows": _build_rows(offset=9000, length=40),
    }

    unauthorized = client.post("/api/v1/drift/evaluate", json=payload)
    _assert_error_contract(
        unauthorized,
        expected_status=401,
        expected_code="unauthorized",
        expected_message="api_key_invalid",
    )

    invalid_key = client.post("/api/v1/drift/evaluate", headers={"X-API-Key": "wrong"}, json=payload)
    _assert_error_contract(
        invalid_key,
        expected_status=401,
        expected_code="unauthorized",
        expected_message="api_key_invalid",
    )

    authorized = client.post("/api/v1/drift/evaluate", headers={"X-API-Key": "phase1-secret"}, json=payload)
    assert authorized.status_code == 200


def test_phase1_error_contract_response() -> None:
    """Return normalized bad-request payloads for domain validation failures."""
    payload = {
        "reference_target": [1] * 40,
        "current_target": [2] * 40,
        "reference_prediction": [1] * 39,
        "current_prediction": [2] * 40,
    }

    response = client.post("/api/v1/drift/concept", json=payload)
    _assert_error_contract(response, expected_status=400, expected_code="bad_request")
