# Generated by GitHub Copilot
"""Runtime configuration for the drift-watch backend."""

from dataclasses import dataclass
import os
from typing import List


def _parse_csv(raw_value: str) -> List[str]:
    """Parse a comma-separated string into normalized entries."""
    return [item.strip() for item in raw_value.split(",") if item.strip()]


def _parse_bool(raw_value: str, default: bool) -> bool:
    """Parse boolean values from environment variables safely."""
    if raw_value is None:
        return default
    lowered = raw_value.strip().lower()
    if lowered in {"1", "true", "yes", "on"}:
        return True
    if lowered in {"0", "false", "no", "off"}:
        return False
    return default


@dataclass(frozen=True)
class Settings:
    """Application settings loaded from environment variables."""

    app_env: str
    allowed_hosts: List[str]
    cors_origins: List[str]
    max_payload_bytes: int
    gzip_minimum_size: int
    enable_hsts: bool
    api_key: str
    port: int


def load_settings() -> Settings:
    """Load validated settings with production-safe defaults."""
    app_env = os.getenv("DRIFT_ENV", "development").strip().lower() or "development"

    allowed_hosts = _parse_csv(
        os.getenv("DRIFT_ALLOWED_HOSTS", "localhost,127.0.0.1,backend,testserver")
    )
    cors_origins = _parse_csv(
        os.getenv("DRIFT_CORS_ORIGINS", "http://localhost:8080,http://127.0.0.1:8080")
    )

    max_payload_bytes = int(os.getenv("DRIFT_MAX_PAYLOAD_BYTES", "10485760"))
    gzip_minimum_size = int(os.getenv("DRIFT_GZIP_MINIMUM_SIZE", "1024"))
    enable_hsts = _parse_bool(os.getenv("DRIFT_ENABLE_HSTS"), default=False)
    api_key = os.getenv("DRIFT_API_KEY", "").strip()
    port = int(os.getenv("DRIFT_PORT", "8000"))

    return Settings(
        app_env=app_env,
        allowed_hosts=allowed_hosts,
        cors_origins=cors_origins,
        max_payload_bytes=max_payload_bytes,
        gzip_minimum_size=gzip_minimum_size,
        enable_hsts=enable_hsts,
        api_key=api_key,
        port=port,
    )
