# Generated by GitHub Copilot
"""Runtime configuration for the drift-watch backend."""

from dataclasses import dataclass
import os
from typing import List


def _parse_csv(raw_value: str) -> List[str]:
    """Parse a comma-separated string into normalized entries."""
    return [item.strip() for item in raw_value.split(",") if item.strip()]


def _parse_bool(raw_value: str, default: bool) -> bool:
    """Parse boolean values from environment variables safely."""
    if raw_value is None:
        return default
    lowered = raw_value.strip().lower()
    if lowered in {"1", "true", "yes", "on"}:
        return True
    if lowered in {"0", "false", "no", "off"}:
        return False
    return default


def _parse_int(raw_value: str | None, default: int, min_value: int) -> int:
    """Parse constrained integer settings from environment values."""
    if raw_value is None:
        return default
    try:
        parsed = int(raw_value)
    except ValueError:
        return default
    return max(min_value, parsed)


@dataclass(frozen=True)
class Settings:
    """Application settings loaded from environment variables."""

    app_env: str
    allowed_hosts: List[str]
    cors_origins: List[str]
    max_payload_bytes: int
    gzip_minimum_size: int
    enable_hsts: bool
    api_key: str
    rate_limit_per_minute: int
    port: int


def load_settings() -> Settings:
    """Load validated settings with production-safe defaults."""
    app_env = os.getenv("DRIFT_ENV", "development").strip().lower() or "development"

    allowed_hosts = _parse_csv(
        os.getenv("DRIFT_ALLOWED_HOSTS", "localhost,127.0.0.1,backend,testserver")
    )
    cors_origins = _parse_csv(
        os.getenv("DRIFT_CORS_ORIGINS", "http://localhost:8080,http://127.0.0.1:8080")
    )

    max_payload_bytes = _parse_int(
        os.getenv("DRIFT_MAX_PAYLOAD_BYTES"),
        default=10_485_760,
        min_value=1_048_576,
    )
    gzip_minimum_size = _parse_int(
        os.getenv("DRIFT_GZIP_MINIMUM_SIZE"),
        default=1024,
        min_value=256,
    )
    enable_hsts = _parse_bool(os.getenv("DRIFT_ENABLE_HSTS"), default=False)
    api_key = os.getenv("DRIFT_API_KEY", "").strip()
    rate_limit_per_minute = _parse_int(
        os.getenv("DRIFT_RATE_LIMIT_PER_MINUTE"),
        default=180,
        min_value=10,
    )
    port = _parse_int(os.getenv("DRIFT_PORT"), default=8000, min_value=1)

    return Settings(
        app_env=app_env,
        allowed_hosts=allowed_hosts,
        cors_origins=cors_origins,
        max_payload_bytes=max_payload_bytes,
        gzip_minimum_size=gzip_minimum_size,
        enable_hsts=enable_hsts,
        api_key=api_key,
        rate_limit_per_minute=rate_limit_per_minute,
        port=port,
    )
