# Generated by GitHub Copilot
"""Core statistical drift functions with deterministic behavior."""

from bisect import bisect_right
from collections import Counter
from math import isfinite, log2
from typing import Dict, Iterable, List, Tuple


def _coerce_float_values(values: Iterable[object]) -> List[float]:
    """Convert mixed values to finite float values while skipping invalid entries."""
    cleaned: List[float] = []
    for value in values:
        if value is None:
            continue
        try:
            converted = float(value)
        except (TypeError, ValueError):
            continue
        if isfinite(converted):
            cleaned.append(converted)
    return cleaned


def _quantile_edges(values: List[float], bins: int) -> List[float]:
    """Build stable quantile bin edges for numeric distribution comparison."""
    if not values:
        return [0.0, 1.0]

    sorted_values = sorted(values)
    last_index = len(sorted_values) - 1
    edges = [sorted_values[0]]

    for idx in range(1, bins):
        position = (idx * last_index) / bins
        lower = int(position)
        upper = min(lower + 1, last_index)
        fraction = position - lower
        interpolated = sorted_values[lower] + (
            (sorted_values[upper] - sorted_values[lower]) * fraction
        )
        edges.append(interpolated)

    edges.append(sorted_values[-1])

    for index in range(1, len(edges)):
        if edges[index] <= edges[index - 1]:
            edges[index] = edges[index - 1] + 1e-9

    return edges


def _histogram(values: List[float], edges: List[float]) -> List[int]:
    """Count observations inside bins defined by edges."""
    counts = [0 for _ in range(len(edges) - 1)]
    for value in values:
        bin_index = bisect_right(edges, value) - 1
        bounded_index = max(0, min(len(counts) - 1, bin_index))
        counts[bounded_index] += 1
    return counts


def _normalize_counts(counts: List[int], epsilon: float = 1e-6) -> List[float]:
    """Convert counts into smoothed probabilities."""
    smoothed = [count + epsilon for count in counts]
    total = sum(smoothed)
    return [value / total for value in smoothed]


def population_stability_index(reference_probs: List[float], current_probs: List[float]) -> float:
    """Compute PSI score between two aligned probability vectors."""
    psi_total = 0.0
    for ref_prob, cur_prob in zip(reference_probs, current_probs):
        psi_total += (cur_prob - ref_prob) * log2(cur_prob / ref_prob)
    return max(0.0, psi_total)


def kolmogorov_smirnov_statistic(reference_values: List[float], current_values: List[float]) -> float:
    """Compute KS statistic using empirical CDF distance."""
    if not reference_values or not current_values:
        return 0.0

    ref_sorted = sorted(reference_values)
    cur_sorted = sorted(current_values)
    ref_len = len(ref_sorted)
    cur_len = len(cur_sorted)

    ref_index = 0
    cur_index = 0
    max_distance = 0.0

    while ref_index < ref_len and cur_index < cur_len:
        if ref_sorted[ref_index] <= cur_sorted[cur_index]:
            pivot = ref_sorted[ref_index]
            while ref_index < ref_len and ref_sorted[ref_index] <= pivot:
                ref_index += 1
        else:
            pivot = cur_sorted[cur_index]
            while cur_index < cur_len and cur_sorted[cur_index] <= pivot:
                cur_index += 1

        ref_cdf = ref_index / ref_len
        cur_cdf = cur_index / cur_len
        max_distance = max(max_distance, abs(ref_cdf - cur_cdf))

    max_distance = max(max_distance, abs(1.0 - (cur_index / cur_len)))
    max_distance = max(max_distance, abs((ref_index / ref_len) - 1.0))
    return max_distance


def jensen_shannon_divergence(reference_probs: List[float], current_probs: List[float]) -> float:
    """Compute bounded Jensen-Shannon divergence in base-2 space."""
    midpoint = [(ref + cur) / 2.0 for ref, cur in zip(reference_probs, current_probs)]

    def _kl_divergence(p_values: List[float], q_values: List[float]) -> float:
        """Compute KL divergence with implicit smoothing from caller."""
        total = 0.0
        for p_value, q_value in zip(p_values, q_values):
            total += p_value * log2(p_value / q_value)
        return total

    jsd = 0.5 * _kl_divergence(reference_probs, midpoint) + 0.5 * _kl_divergence(
        current_probs, midpoint
    )
    return max(0.0, min(1.0, jsd))


def _categorical_probabilities(reference_values: List[object], current_values: List[object]) -> Tuple[List[float], List[float]]:
    """Return aligned category probability vectors for drift scoring."""
    reference_counter = Counter(str(item) for item in reference_values if item is not None)
    current_counter = Counter(str(item) for item in current_values if item is not None)

    categories = sorted(set(reference_counter.keys()) | set(current_counter.keys()))
    if not categories:
        categories = ["__missing__"]

    reference_counts = [reference_counter.get(category, 0) for category in categories]
    current_counts = [current_counter.get(category, 0) for category in categories]

    return _normalize_counts(reference_counts), _normalize_counts(current_counts)


def evaluate_numeric_drift(
    reference_values: Iterable[object],
    current_values: Iterable[object],
    bins: int,
) -> Dict[str, float | int]:
    """Evaluate numeric drift using PSI and KS and return normalized score."""
    reference_clean = _coerce_float_values(reference_values)
    current_clean = _coerce_float_values(current_values)

    if len(reference_clean) < 10 or len(current_clean) < 10:
        raise ValueError("numeric drift requires at least 10 valid numeric points per window")

    combined_values = reference_clean + current_clean
    edges = _quantile_edges(combined_values, bins=bins)
    reference_hist = _histogram(reference_clean, edges)
    current_hist = _histogram(current_clean, edges)

    reference_probs = _normalize_counts(reference_hist)
    current_probs = _normalize_counts(current_hist)

    psi_score = population_stability_index(reference_probs, current_probs)
    ks_score = kolmogorov_smirnov_statistic(reference_clean, current_clean)

    bounded_psi = max(0.0, min(1.0, psi_score))
    bounded_ks = max(0.0, min(1.0, ks_score))
    combined_score = min(1.0, (0.65 * bounded_psi) + (0.35 * bounded_ks))

    return {
        "drift_score": round(combined_score, 6),
        "psi": round(psi_score, 6),
        "ks": round(ks_score, 6),
        "reference_count": len(reference_clean),
        "current_count": len(current_clean),
    }


def evaluate_categorical_drift(
    reference_values: Iterable[object],
    current_values: Iterable[object],
) -> Dict[str, float | int]:
    """Evaluate categorical drift using Jensen-Shannon divergence."""
    reference_list = [item for item in reference_values if item is not None]
    current_list = [item for item in current_values if item is not None]

    if len(reference_list) < 10 or len(current_list) < 10:
        raise ValueError("categorical drift requires at least 10 valid points per window")

    reference_probs, current_probs = _categorical_probabilities(reference_list, current_list)
    jsd_score = jensen_shannon_divergence(reference_probs, current_probs)

    return {
        "drift_score": round(jsd_score, 6),
        "js_divergence": round(jsd_score, 6),
        "reference_count": len(reference_list),
        "current_count": len(current_list),
    }
