# Generated by GitHub Copilot
"""FastAPI entrypoint for drift-watch backend."""

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.middleware.gzip import GZipMiddleware
from starlette.middleware.trustedhost import TrustedHostMiddleware

from app.config import load_settings
from app.middleware import HSTSMiddleware, PayloadSizeLimitMiddleware
from app.models import (
    ConceptDriftRequest,
    ConceptDriftResponse,
    DriftEvaluationRequest,
    DriftEvaluationResponse,
)
from app.service import evaluate_concept_drift, evaluate_feature_drift

settings = load_settings()

app = FastAPI(
    title="drift-watch API",
    version="0.1.0",
    description="Production-grade feature and concept drift observability API",
)

app.add_middleware(GZipMiddleware, minimum_size=settings.gzip_minimum_size)
app.add_middleware(PayloadSizeLimitMiddleware, max_payload_bytes=settings.max_payload_bytes)

if settings.allowed_hosts:
    app.add_middleware(TrustedHostMiddleware, allowed_hosts=settings.allowed_hosts)

if settings.cors_origins:
    app.add_middleware(
        CORSMiddleware,
        allow_origins=settings.cors_origins,
        allow_methods=["GET", "POST", "OPTIONS"],
        allow_headers=["Authorization", "Content-Type"],
        allow_credentials=False,
    )

if settings.enable_hsts and settings.app_env == "production":
    app.add_middleware(HSTSMiddleware)


@app.get("/", tags=["system"])
def root() -> dict[str, str]:
    """Return API metadata for root checks."""
    return {"service": "drift-watch", "version": "0.1.0", "status": "ok"}


@app.get("/health", tags=["system"])
def health() -> dict[str, str]:
    """Liveness probe endpoint."""
    return {"status": "ok"}


@app.get("/ready", tags=["system"])
def ready() -> dict[str, str]:
    """Readiness probe endpoint."""
    return {"status": "ready"}


@app.post("/api/v1/drift/evaluate", response_model=DriftEvaluationResponse, tags=["drift"])
def evaluate_drift(payload: DriftEvaluationRequest) -> DriftEvaluationResponse:
    """Evaluate feature drift from schema-driven payloads."""
    try:
        return evaluate_feature_drift(payload)
    except ValueError as error:
        raise HTTPException(status_code=400, detail=str(error)) from error


@app.post("/api/v1/drift/concept", response_model=ConceptDriftResponse, tags=["drift"])
def evaluate_concept(payload: ConceptDriftRequest) -> ConceptDriftResponse:
    """Evaluate concept drift and optional residual shift."""
    try:
        return evaluate_concept_drift(payload)
    except ValueError as error:
        raise HTTPException(status_code=400, detail=str(error)) from error
