# Generated by GitHub Copilot
"""FastAPI entrypoint for drift-watch backend."""

from fastapi import Depends, FastAPI, Header, HTTPException, Request
from fastapi.exceptions import RequestValidationError
from fastapi.middleware.cors import CORSMiddleware
from fastapi.middleware.gzip import GZipMiddleware
from fastapi.responses import JSONResponse
from starlette.exceptions import HTTPException as StarletteHTTPException
from starlette.middleware.trustedhost import TrustedHostMiddleware

from app.config import load_settings
from app.middleware import PayloadSizeLimitMiddleware, RequestContextMiddleware, SecurityHeadersMiddleware
from app.models import (
    ConceptDriftRequest,
    ConceptDriftResponse,
    DriftEvaluationRequest,
    DriftEvaluationResponse,
)
from app.service import evaluate_concept_drift, evaluate_feature_drift

settings = load_settings()
AUTH_EXEMPT_PATHS = {
    "/",
    "/health",
    "/ready",
    "/healthz",
    "/readyz",
    "/docs",
    "/openapi.json",
    "/redoc",
}


# Generated by GitHub Copilot
def _request_id_from_request(request: Request) -> str:
    """Read request correlation id from middleware state or fallback headers."""
    request_id = getattr(request.state, "request_id", None)
    if isinstance(request_id, str) and request_id:
        return request_id
    return request.headers.get("X-Request-ID", "unknown")


# Generated by GitHub Copilot
def _build_error_payload(
    request: Request,
    code: str,
    message: str,
    details: object | None = None,
) -> dict[str, object]:
    """Build normalized error payload for API clients and observability tooling."""
    payload: dict[str, object] = {
        "error": {
            "code": code,
            "message": message,
            "request_id": _request_id_from_request(request),
        }
    }
    if details is not None:
        payload["error"]["details"] = details
    return payload


# Generated by GitHub Copilot
def _status_to_error_code(status_code: int) -> str:
    """Map HTTP status codes into stable contract error codes."""
    mapping = {
        400: "bad_request",
        401: "unauthorized",
        403: "forbidden",
        404: "not_found",
        409: "conflict",
        413: "payload_too_large",
        422: "validation_error",
        429: "rate_limited",
    }
    if status_code >= 500:
        return "internal_error"
    return mapping.get(status_code, "request_failed")


# Generated by GitHub Copilot
def _require_api_key(
    request: Request,
    x_api_key: str | None = Header(default=None, alias="X-API-Key"),
) -> None:
    """Enforce optional API key auth for non-probe endpoints."""
    if request.method == "OPTIONS" or request.url.path in AUTH_EXEMPT_PATHS:
        return
    if not settings.api_key:
        return
    if x_api_key != settings.api_key:
        raise HTTPException(status_code=401, detail="api_key_invalid")

app = FastAPI(
    title="drift-watch API",
    version="0.1.0",
    description="Production-grade feature and concept drift observability API",
    dependencies=[Depends(_require_api_key)],
)

app.add_middleware(RequestContextMiddleware)
app.add_middleware(GZipMiddleware, minimum_size=settings.gzip_minimum_size)
app.add_middleware(PayloadSizeLimitMiddleware, max_payload_bytes=settings.max_payload_bytes)
app.add_middleware(
    SecurityHeadersMiddleware,
    enable_hsts=settings.enable_hsts and settings.app_env == "production",
)

if settings.allowed_hosts:
    app.add_middleware(TrustedHostMiddleware, allowed_hosts=settings.allowed_hosts)

if settings.cors_origins:
    app.add_middleware(
        CORSMiddleware,
        allow_origins=settings.cors_origins,
        allow_methods=["GET", "POST", "OPTIONS"],
        allow_headers=["Authorization", "Content-Type", "X-Request-ID", "X-API-Key"],
        allow_credentials=False,
    )


# Generated by GitHub Copilot
@app.exception_handler(StarletteHTTPException)
@app.exception_handler(HTTPException)
async def handle_http_exception(request: Request, exc: HTTPException) -> JSONResponse:
    """Return normalized error payloads for HTTP exceptions."""
    message = str(exc.detail) if exc.detail is not None else "request_failed"
    return JSONResponse(
        status_code=exc.status_code,
        content=_build_error_payload(
            request=request,
            code=_status_to_error_code(exc.status_code),
            message=message,
        ),
    )


# Generated by GitHub Copilot
@app.exception_handler(RequestValidationError)
async def handle_validation_exception(request: Request, exc: RequestValidationError) -> JSONResponse:
    """Return normalized validation error payloads with structured details."""
    return JSONResponse(
        status_code=422,
        content=_build_error_payload(
            request=request,
            code="validation_error",
            message="request_validation_failed",
            details=exc.errors(),
        ),
    )


# Generated by GitHub Copilot
@app.exception_handler(Exception)
async def handle_unexpected_exception(request: Request, _: Exception) -> JSONResponse:
    """Return normalized payloads for unexpected internal server errors."""
    return JSONResponse(
        status_code=500,
        content=_build_error_payload(
            request=request,
            code="internal_error",
            message="internal_server_error",
        ),
    )

@app.get("/", tags=["system"])
def root() -> dict[str, str]:
    """Return API metadata for root checks."""
    return {"service": "drift-watch", "version": "0.1.0", "status": "ok"}


@app.get("/health", tags=["system"])
def health() -> dict[str, str]:
    """Liveness probe endpoint."""
    return {"status": "ok"}


@app.get("/ready", tags=["system"])
def ready() -> dict[str, str]:
    """Readiness probe endpoint."""
    return {"status": "ready"}


# Generated by GitHub Copilot
@app.get("/healthz", tags=["system"], include_in_schema=False)
def healthz() -> dict[str, str]:
    """Compatibility alias for health probes expecting /healthz."""
    return health()


# Generated by GitHub Copilot
@app.get("/readyz", tags=["system"], include_in_schema=False)
def readyz() -> dict[str, str]:
    """Compatibility alias for readiness probes expecting /readyz."""
    return ready()


@app.post("/api/v1/drift/evaluate", response_model=DriftEvaluationResponse, tags=["drift"])
def evaluate_drift(payload: DriftEvaluationRequest) -> DriftEvaluationResponse:
    """Evaluate feature drift from schema-driven payloads."""
    try:
        return evaluate_feature_drift(payload)
    except ValueError as error:
        raise HTTPException(status_code=400, detail=str(error)) from error


@app.post("/api/v1/drift/concept", response_model=ConceptDriftResponse, tags=["drift"])
def evaluate_concept(payload: ConceptDriftRequest) -> ConceptDriftResponse:
    """Evaluate concept drift and optional residual shift."""
    try:
        return evaluate_concept_drift(payload)
    except ValueError as error:
        raise HTTPException(status_code=400, detail=str(error)) from error
