# Generated by GitHub Copilot
"""Middleware utilities for API hardening."""

from collections import defaultdict, deque
from time import monotonic
from typing import Deque, Dict
from uuid import uuid4

from starlette.middleware.base import BaseHTTPMiddleware
from starlette.requests import Request
from starlette.responses import JSONResponse, Response


def _request_id_from_request(request: Request) -> str:
    """Resolve request id from middleware state or request headers."""
    request_id = getattr(request.state, "request_id", None)
    if isinstance(request_id, str) and request_id:
        return request_id
    return request.headers.get("X-Request-ID", str(uuid4()))


def _error_payload(request: Request, code: str, message: str) -> dict[str, object]:
    """Build normalized middleware error payloads."""
    return {
        "error": {
            "code": code,
            "message": message,
            "request_id": _request_id_from_request(request),
        }
    }


class PayloadSizeLimitMiddleware(BaseHTTPMiddleware):
    """Reject requests when the declared payload exceeds the configured limit."""

    def __init__(self, app, max_payload_bytes: int):
        super().__init__(app)
        self.max_payload_bytes = max_payload_bytes

    async def dispatch(self, request: Request, call_next):
        """Intercept requests and return HTTP 413 for oversized payloads."""
        content_length = request.headers.get("content-length")
        if content_length is not None:
            try:
                parsed = int(content_length)
            except ValueError:
                return JSONResponse(
                    status_code=400,
                    content=_error_payload(request, code="bad_request", message="invalid content-length header"),
                )

            if parsed > self.max_payload_bytes:
                return JSONResponse(
                    status_code=413,
                    content=_error_payload(request, code="payload_too_large", message="request payload too large"),
                )

        return await call_next(request)


class HSTSMiddleware(BaseHTTPMiddleware):
    """Attach HSTS headers in production HTTPS deployments."""

    async def dispatch(self, request: Request, call_next):
        """Add strict transport security response header."""
        response: Response = await call_next(request)
        response.headers["Strict-Transport-Security"] = (
            "max-age=31536000; includeSubDomains"
        )
        return response


# Generated by GitHub Copilot
class SecurityHeadersMiddleware(BaseHTTPMiddleware):
    """Attach baseline security headers and optional HSTS to API responses."""

    def __init__(self, app, enable_hsts: bool):
        super().__init__(app)
        self.enable_hsts = enable_hsts

    async def dispatch(self, request: Request, call_next):
        """Set defensive browser headers for all HTTP responses."""
        response: Response = await call_next(request)
        response.headers["X-Content-Type-Options"] = "nosniff"
        response.headers["X-Frame-Options"] = "DENY"
        response.headers["Referrer-Policy"] = "strict-origin-when-cross-origin"
        response.headers["Permissions-Policy"] = "camera=(), microphone=(), geolocation=()"
        response.headers["Content-Security-Policy"] = "default-src 'none'; frame-ancestors 'none'; base-uri 'none'"
        if self.enable_hsts:
            response.headers["Strict-Transport-Security"] = "max-age=31536000; includeSubDomains"
        return response


# Generated by GitHub Copilot
class RequestContextMiddleware(BaseHTTPMiddleware):
    """Attach correlation identifiers to request state and response headers."""

    async def dispatch(self, request: Request, call_next):
        """Propagate incoming request id or generate one for downstream tracing."""
        request_id = request.headers.get("X-Request-ID", str(uuid4()))
        request.state.request_id = request_id

        response: Response = await call_next(request)
        response.headers["X-Request-ID"] = request_id
        return response


class SimpleRateLimitMiddleware(BaseHTTPMiddleware):
    """Apply an in-memory fixed-window limit per client IP."""

    def __init__(self, app, max_requests_per_minute: int, exempt_paths: set[str] | None = None):
        super().__init__(app)
        self.max_requests_per_minute = max_requests_per_minute
        self.window_seconds = 60.0
        self.exempt_paths = exempt_paths or set()
        self.request_log: Dict[str, Deque[float]] = defaultdict(deque)

    async def dispatch(self, request: Request, call_next):
        """Track request timestamps and block traffic above configured limits."""
        if request.method == "OPTIONS" or request.url.path in self.exempt_paths:
            return await call_next(request)

        client_ip = request.client.host if request.client else "unknown"
        now = monotonic()
        bucket = self.request_log[client_ip]

        while bucket and (now - bucket[0]) > self.window_seconds:
            bucket.popleft()

        if len(bucket) >= self.max_requests_per_minute:
            return JSONResponse(
                status_code=429,
                content=_error_payload(request, code="rate_limited", message="rate_limited"),
                headers={"Retry-After": "60"},
            )

        bucket.append(now)
        return await call_next(request)
