# Generated by GitHub Copilot
"""Middleware utilities for API hardening."""

from uuid import uuid4

from starlette.middleware.base import BaseHTTPMiddleware
from starlette.requests import Request
from starlette.responses import JSONResponse, Response


class PayloadSizeLimitMiddleware(BaseHTTPMiddleware):
    """Reject requests when the declared payload exceeds the configured limit."""

    def __init__(self, app, max_payload_bytes: int):
        super().__init__(app)
        self.max_payload_bytes = max_payload_bytes

    async def dispatch(self, request: Request, call_next):
        """Intercept requests and return HTTP 413 for oversized payloads."""
        content_length = request.headers.get("content-length")
        if content_length and content_length.isdigit():
            if int(content_length) > self.max_payload_bytes:
                return JSONResponse(
                    status_code=413,
                    content={
                        "detail": f"payload too large; limit is {self.max_payload_bytes} bytes"
                    },
                )
        return await call_next(request)


class HSTSMiddleware(BaseHTTPMiddleware):
    """Attach HSTS headers in production HTTPS deployments."""

    async def dispatch(self, request: Request, call_next):
        """Add strict transport security response header."""
        response: Response = await call_next(request)
        response.headers["Strict-Transport-Security"] = (
            "max-age=31536000; includeSubDomains"
        )
        return response


# Generated by GitHub Copilot
class SecurityHeadersMiddleware(BaseHTTPMiddleware):
    """Attach baseline security headers and optional HSTS to API responses."""

    def __init__(self, app, enable_hsts: bool):
        super().__init__(app)
        self.enable_hsts = enable_hsts

    async def dispatch(self, request: Request, call_next):
        """Set defensive browser headers for all HTTP responses."""
        response: Response = await call_next(request)
        response.headers["X-Content-Type-Options"] = "nosniff"
        response.headers["X-Frame-Options"] = "DENY"
        response.headers["Referrer-Policy"] = "strict-origin-when-cross-origin"
        response.headers["Permissions-Policy"] = "camera=(), microphone=(), geolocation=()"
        response.headers["Content-Security-Policy"] = "default-src 'none'; frame-ancestors 'none'; base-uri 'none'"
        if self.enable_hsts:
            response.headers["Strict-Transport-Security"] = "max-age=31536000; includeSubDomains"
        return response


# Generated by GitHub Copilot
class RequestContextMiddleware(BaseHTTPMiddleware):
    """Attach correlation identifiers to request state and response headers."""

    async def dispatch(self, request: Request, call_next):
        """Propagate incoming request id or generate one for downstream tracing."""
        request_id = request.headers.get("X-Request-ID", str(uuid4()))
        request.state.request_id = request_id

        response: Response = await call_next(request)
        response.headers["X-Request-ID"] = request_id
        return response
