# Generated by GitHub Copilot
"""Middleware utilities for API hardening."""

from starlette.middleware.base import BaseHTTPMiddleware
from starlette.requests import Request
from starlette.responses import JSONResponse, Response


class PayloadSizeLimitMiddleware(BaseHTTPMiddleware):
    """Reject requests when the declared payload exceeds the configured limit."""

    def __init__(self, app, max_payload_bytes: int):
        super().__init__(app)
        self.max_payload_bytes = max_payload_bytes

    async def dispatch(self, request: Request, call_next):
        """Intercept requests and return HTTP 413 for oversized payloads."""
        content_length = request.headers.get("content-length")
        if content_length and content_length.isdigit():
            if int(content_length) > self.max_payload_bytes:
                return JSONResponse(
                    status_code=413,
                    content={
                        "detail": f"payload too large; limit is {self.max_payload_bytes} bytes"
                    },
                )
        return await call_next(request)


class HSTSMiddleware(BaseHTTPMiddleware):
    """Attach HSTS headers in production HTTPS deployments."""

    async def dispatch(self, request: Request, call_next):
        """Add strict transport security response header."""
        response: Response = await call_next(request)
        response.headers["Strict-Transport-Security"] = (
            "max-age=31536000; includeSubDomains"
        )
        return response
