# Generated by GitHub Copilot
"""Pydantic models for drift-watch API contracts."""

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, field_validator, model_validator


class FeatureKind(str, Enum):
    """Supported feature types for drift evaluation."""

    numeric = "numeric"
    categorical = "categorical"


class DriftFeatureSchema(BaseModel):
    """Configuration for evaluating drift on one feature."""

    name: str = Field(min_length=1, max_length=64)
    kind: FeatureKind
    bins: int = Field(default=10, ge=5, le=50)
    alert_threshold: float = Field(default=0.2, ge=0.0, le=1.0)

    @field_validator("name")
    @classmethod
    def validate_name(cls, value: str) -> str:
        """Reject unsafe or malformed feature names."""
        cleaned = value.strip()
        if not cleaned.replace("_", "").replace("-", "").isalnum():
            raise ValueError("feature name must be alphanumeric with optional _ or -")
        return cleaned


class DriftEvaluationRequest(BaseModel):
    """Request payload for feature drift evaluation."""

    schema_name: str = Field(min_length=3, max_length=128)
    features: List[DriftFeatureSchema] = Field(min_length=1, max_length=128)
    reference_rows: List[Dict[str, Any]] = Field(min_length=30, max_length=10000)
    current_rows: List[Dict[str, Any]] = Field(min_length=30, max_length=10000)

    @model_validator(mode="after")
    def validate_feature_uniqueness(self) -> "DriftEvaluationRequest":
        """Ensure each feature name appears only once in a request."""
        feature_names = [item.name for item in self.features]
        if len(feature_names) != len(set(feature_names)):
            raise ValueError("feature names must be unique")
        return self


class FeatureDriftResult(BaseModel):
    """Computed drift result for one feature."""

    feature_name: str
    kind: FeatureKind
    method: str
    drift_score: float
    threshold: float
    drift_detected: bool
    details: Dict[str, float | int | str]


class DriftEvaluationSummary(BaseModel):
    """Top-level drift evaluation summary."""

    schema_name: str
    evaluated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    total_features: int
    drifted_features: int
    status: str


class DriftEvaluationResponse(BaseModel):
    """API response for feature drift evaluation."""

    summary: DriftEvaluationSummary
    results: List[FeatureDriftResult]


class ConceptDriftRequest(BaseModel):
    """Request payload for concept drift evaluation."""

    reference_target: List[Any] = Field(min_length=30, max_length=50000)
    current_target: List[Any] = Field(min_length=30, max_length=50000)
    reference_prediction: Optional[List[Any]] = Field(default=None, max_length=50000)
    current_prediction: Optional[List[Any]] = Field(default=None, max_length=50000)
    alert_threshold: float = Field(default=0.2, ge=0.0, le=1.0)


class ConceptMetricResult(BaseModel):
    """Drift metric result for concept and residual checks."""

    metric_name: str
    method: str
    drift_score: float
    threshold: float
    drift_detected: bool
    details: Dict[str, float | int | str]


class ConceptDriftResponse(BaseModel):
    """API response for concept drift evaluation."""

    evaluated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    status: str
    results: List[ConceptMetricResult]
