# Generated by GitHub Copilot
"""Service layer for drift request orchestration."""

from typing import Any, Dict, Iterable, List, Optional

from app.drift import evaluate_categorical_drift, evaluate_numeric_drift
from app.models import (
    ConceptDriftRequest,
    ConceptDriftResponse,
    ConceptMetricResult,
    DriftEvaluationRequest,
    DriftEvaluationResponse,
    DriftEvaluationSummary,
    FeatureDriftResult,
    FeatureKind,
)


def _extract_column(rows: List[Dict[str, Any]], feature_name: str) -> List[Any]:
    """Extract one feature column from row-based payloads."""
    return [row.get(feature_name) for row in rows]


def _is_numeric_sequence(values: Iterable[Any]) -> bool:
    """Detect whether a sequence is fully numeric for residual analysis."""
    valid_count = 0
    for value in values:
        if value is None:
            continue
        try:
            float(value)
        except (TypeError, ValueError):
            return False
        valid_count += 1
    return valid_count > 0


def _to_float_list(values: Iterable[Any]) -> List[float]:
    """Convert values to float list and skip null entries."""
    converted: List[float] = []
    for value in values:
        if value is None:
            continue
        converted.append(float(value))
    return converted


def evaluate_feature_drift(payload: DriftEvaluationRequest) -> DriftEvaluationResponse:
    """Evaluate drift for all configured features in the payload."""
    results: List[FeatureDriftResult] = []

    for feature in payload.features:
        reference_values = _extract_column(payload.reference_rows, feature.name)
        current_values = _extract_column(payload.current_rows, feature.name)

        if feature.kind == FeatureKind.numeric:
            metric_payload = evaluate_numeric_drift(
                reference_values=reference_values,
                current_values=current_values,
                bins=feature.bins,
            )
            method_name = "psi+ks"
        else:
            metric_payload = evaluate_categorical_drift(
                reference_values=reference_values,
                current_values=current_values,
            )
            method_name = "js-divergence"

        drift_score = float(metric_payload["drift_score"])
        results.append(
            FeatureDriftResult(
                feature_name=feature.name,
                kind=feature.kind,
                method=method_name,
                drift_score=drift_score,
                threshold=feature.alert_threshold,
                drift_detected=drift_score >= feature.alert_threshold,
                details={
                    key: value
                    for key, value in metric_payload.items()
                    if key != "drift_score"
                },
            )
        )

    drifted_count = sum(1 for item in results if item.drift_detected)
    summary = DriftEvaluationSummary(
        schema_name=payload.schema_name,
        total_features=len(results),
        drifted_features=drifted_count,
        status="alert" if drifted_count > 0 else "stable",
    )

    return DriftEvaluationResponse(summary=summary, results=results)


def _safe_numeric_drift(
    metric_name: str,
    reference_values: List[Any],
    current_values: List[Any],
    threshold: float,
) -> Optional[ConceptMetricResult]:
    """Compute numeric concept metric when values can be interpreted as numbers."""
    if not _is_numeric_sequence(reference_values) or not _is_numeric_sequence(current_values):
        return None

    metric_payload = evaluate_numeric_drift(reference_values, current_values, bins=10)
    drift_score = float(metric_payload["drift_score"])
    return ConceptMetricResult(
        metric_name=metric_name,
        method="psi+ks",
        drift_score=drift_score,
        threshold=threshold,
        drift_detected=drift_score >= threshold,
        details={
            key: value
            for key, value in metric_payload.items()
            if key != "drift_score"
        },
    )


def evaluate_concept_drift(payload: ConceptDriftRequest) -> ConceptDriftResponse:
    """Evaluate concept drift on target distributions and residual behavior."""
    results: List[ConceptMetricResult] = []

    target_metric = _safe_numeric_drift(
        metric_name="target_distribution_shift",
        reference_values=payload.reference_target,
        current_values=payload.current_target,
        threshold=payload.alert_threshold,
    )

    if target_metric is None:
        target_distribution = evaluate_categorical_drift(
            reference_values=payload.reference_target,
            current_values=payload.current_target,
        )
        target_score = float(target_distribution["drift_score"])
        target_metric = ConceptMetricResult(
            metric_name="target_distribution_shift",
            method="js-divergence",
            drift_score=target_score,
            threshold=payload.alert_threshold,
            drift_detected=target_score >= payload.alert_threshold,
            details={
                key: value
                for key, value in target_distribution.items()
                if key != "drift_score"
            },
        )

    results.append(target_metric)

    if payload.reference_prediction is not None and payload.current_prediction is not None:
        if len(payload.reference_prediction) != len(payload.reference_target):
            raise ValueError("reference_prediction length must match reference_target")
        if len(payload.current_prediction) != len(payload.current_target):
            raise ValueError("current_prediction length must match current_target")

        if _is_numeric_sequence(payload.reference_target) and _is_numeric_sequence(
            payload.current_target
        ) and _is_numeric_sequence(payload.reference_prediction) and _is_numeric_sequence(
            payload.current_prediction
        ):
            reference_residuals = [
                abs(target - prediction)
                for target, prediction in zip(
                    _to_float_list(payload.reference_target),
                    _to_float_list(payload.reference_prediction),
                )
            ]
            current_residuals = [
                abs(target - prediction)
                for target, prediction in zip(
                    _to_float_list(payload.current_target),
                    _to_float_list(payload.current_prediction),
                )
            ]

            residual_metric = _safe_numeric_drift(
                metric_name="residual_distribution_shift",
                reference_values=reference_residuals,
                current_values=current_residuals,
                threshold=payload.alert_threshold,
            )
            if residual_metric is not None:
                results.append(residual_metric)

    has_alert = any(metric.drift_detected for metric in results)
    return ConceptDriftResponse(status="alert" if has_alert else "stable", results=results)
