// Generated by GitHub Copilot
import { FormEvent, useMemo, useState } from "react";

import { MetricCard } from "./components/MetricCard";
import { DriftRequest, DriftResponse, evaluateDrift } from "./lib/api";

/**
 * Generated by GitHub Copilot
 * Build deterministic demo rows to let users run the dashboard instantly.
 */
function buildDemoRows(offset: number, count: number): Array<Record<string, unknown>> {
  const rows: Array<Record<string, unknown>> = [];
  for (let index = 0; index < count; index += 1) {
    rows.push({
      income: 50000 + index * 100 + offset,
      transactions: 12 + (index % 6) + Math.floor(offset / 1000),
      region: index % 3 === 0 ? "east" : index % 3 === 1 ? "west" : "south"
    });
  }
  return rows;
}

const defaultPayload: DriftRequest = {
  schema_name: "credit-risk-model-v1",
  features: [
    { name: "income", kind: "numeric", bins: 10, alert_threshold: 0.15 },
    { name: "transactions", kind: "numeric", bins: 10, alert_threshold: 0.15 },
    { name: "region", kind: "categorical", alert_threshold: 0.12 }
  ],
  reference_rows: buildDemoRows(0, 90),
  current_rows: buildDemoRows(9000, 90)
};

/**
 * Generated by GitHub Copilot
 * Main dashboard for creating and evaluating drift requests.
 */
export default function App(): JSX.Element {
  const [schemaName, setSchemaName] = useState(defaultPayload.schema_name);
  const [featuresJson, setFeaturesJson] = useState(
    JSON.stringify(defaultPayload.features, null, 2)
  );
  const [referenceJson, setReferenceJson] = useState(
    JSON.stringify(defaultPayload.reference_rows, null, 2)
  );
  const [currentJson, setCurrentJson] = useState(
    JSON.stringify(defaultPayload.current_rows, null, 2)
  );

  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<DriftResponse | null>(null);

  const statusLabel = useMemo(() => {
    if (!result) {
      return "No run yet";
    }
    return result.summary.status === "alert" ? "Alert" : "Stable";
  }, [result]);

  /**
   * Generated by GitHub Copilot
   * Parse JSON editors and call drift evaluation endpoint.
   */
  async function handleSubmit(event: FormEvent<HTMLFormElement>): Promise<void> {
    event.preventDefault();
    setError(null);

    try {
      const payload: DriftRequest = {
        schema_name: schemaName.trim(),
        features: JSON.parse(featuresJson),
        reference_rows: JSON.parse(referenceJson),
        current_rows: JSON.parse(currentJson)
      };

      setIsLoading(true);
      const response = await evaluateDrift(payload);
      setResult(response);
    } catch (submitError) {
      const message =
        submitError instanceof Error
          ? submitError.message
          : "Unable to run drift evaluation";
      setError(message);
    } finally {
      setIsLoading(false);
    }
  }

  return (
    <div className="app-shell">
      <header className="hero">
        <p className="eyebrow">Production ML Observability</p>
        <h1>drift-watch control center</h1>
        <p>
          Evaluate feature and concept drift from your current and reference windows,
          then ship alerts before model quality degrades.
        </p>
      </header>

      <main>
        <section className="panel" aria-labelledby="run-evaluation-heading">
          <h2 id="run-evaluation-heading">Run Drift Evaluation</h2>
          <form onSubmit={handleSubmit} className="drift-form">
            <label htmlFor="schemaName">Schema Name</label>
            <input
              id="schemaName"
              value={schemaName}
              onChange={(event) => setSchemaName(event.target.value)}
              required
            />

            <label htmlFor="featuresJson">Feature Config (JSON)</label>
            <textarea
              id="featuresJson"
              value={featuresJson}
              onChange={(event) => setFeaturesJson(event.target.value)}
              rows={10}
              required
            />

            <label htmlFor="referenceJson">Reference Rows (JSON)</label>
            <textarea
              id="referenceJson"
              value={referenceJson}
              onChange={(event) => setReferenceJson(event.target.value)}
              rows={10}
              required
            />

            <label htmlFor="currentJson">Current Rows (JSON)</label>
            <textarea
              id="currentJson"
              value={currentJson}
              onChange={(event) => setCurrentJson(event.target.value)}
              rows={10}
              required
            />

            <button type="submit" disabled={isLoading}>
              {isLoading ? "Evaluating..." : "Evaluate Drift"}
            </button>
          </form>
          {error ? <p className="error-banner" role="alert">{error}</p> : null}
        </section>

        <section className="panel" aria-labelledby="results-heading">
          <h2 id="results-heading">Results</h2>
          <div className="metrics-grid">
            <MetricCard
              title="Run Status"
              value={statusLabel}
              tone={result?.summary.status === "alert" ? "alert" : "ok"}
            />
            <MetricCard
              title="Features Evaluated"
              value={result ? String(result.summary.total_features) : "0"}
              tone="neutral"
            />
            <MetricCard
              title="Drift Alerts"
              value={result ? String(result.summary.drifted_features) : "0"}
              tone={result && result.summary.drifted_features > 0 ? "alert" : "ok"}
            />
          </div>

          {result ? (
            <div className="table-wrap" role="region" aria-label="Feature drift results">
              <table>
                <thead>
                  <tr>
                    <th scope="col">Feature</th>
                    <th scope="col">Kind</th>
                    <th scope="col">Method</th>
                    <th scope="col">Score</th>
                    <th scope="col">Threshold</th>
                    <th scope="col">Status</th>
                  </tr>
                </thead>
                <tbody>
                  {result.results.map((item) => (
                    <tr key={item.feature_name}>
                      <td>{item.feature_name}</td>
                      <td>{item.kind}</td>
                      <td>{item.method}</td>
                      <td>{item.drift_score.toFixed(4)}</td>
                      <td>{item.threshold.toFixed(2)}</td>
                      <td>
                        <strong
                          className={
                            item.drift_detected ? "status-alert" : "status-ok"
                          }
                        >
                          {item.drift_detected ? "Alert" : "Stable"}
                        </strong>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          ) : (
            <p className="placeholder">Run an evaluation to view drift results.</p>
          )}
        </section>
      </main>
    </div>
  );
}
