# Generated by GitHub Copilot
# Initialize local environment and start drift-watch stack.

param(
    [switch]$Production
)

$ErrorActionPreference = "Stop"

if (-not (Test-Path "../.env") -and -not (Test-Path ".env")) {
    if (Test-Path "../.env.example") {
        Copy-Item "../.env.example" "../.env"
    } elseif (Test-Path ".env.example") {
        Copy-Item ".env.example" ".env"
    }
}

if ($Production) {
    docker compose -f ../docker-compose.prod.yml up --build -d
} else {
    docker compose -f ../docker-compose.yml up --build
}
