// Generated by GitHub Copilot
export type FeatureKind = "numeric" | "categorical";

export interface DriftFeature {
  name: string;
  kind: FeatureKind;
  bins?: number;
  alert_threshold: number;
}

export interface DriftRequest {
  schema_name: string;
  features: DriftFeature[];
  reference_rows: Array<Record<string, unknown>>;
  current_rows: Array<Record<string, unknown>>;
}

export interface DriftResult {
  feature_name: string;
  kind: FeatureKind;
  method: string;
  drift_score: number;
  threshold: number;
  drift_detected: boolean;
  details: Record<string, number | string>;
}

export interface DriftResponse {
  summary: {
    schema_name: string;
    evaluated_at: string;
    total_features: number;
    drifted_features: number;
    status: "stable" | "alert";
  };
  results: DriftResult[];
}

const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || "/api";

/**
 * Generated by GitHub Copilot
 * Execute feature drift evaluation against the backend API.
 */
export async function evaluateDrift(payload: DriftRequest): Promise<DriftResponse> {
  const response = await fetch(`${API_BASE_URL}/api/v1/drift/evaluate`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json"
    },
    body: JSON.stringify(payload)
  });

  if (!response.ok) {
    const body = await response.json().catch(() => ({ detail: "unknown error" }));
    throw new Error(body.detail || "drift evaluation failed");
  }

  return (await response.json()) as DriftResponse;
}
